# Machine Learning : Numpy Tutorial
<i>@by utkarsh, Machine Learning Engineer in Easik Inc.<i>

In [1]:
# !pip install numpy and then import the numpy repository.
import numpy as np

## 1. Creating an array using numpy numpy


In [2]:
#numpy array one-dimensional
one_dim_array=np.array([1,2,3,4,5,6,7])
one_dim_array

# output :
# array([1, 2, 3, 4, 5, 6, 7])

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
## numpy array 2-dimensional (like a matrix)
two_dim_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
two_dim_array
# output :
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#numpy array three-dimensional
three_dim_array=np.array([
    [[1,2,3],[1,2,3],[1,5,4]],
    [[1,2,3],[3,5,6],[6,7,8]],
    [[4,4,5],[2,4,5],[5,6,7]]
])
three_dim_array
# Output:
# array([[[1, 2, 3],
#         [1, 2, 3],
#         [1, 5, 4]],

#        [[1, 2, 3],
#         [3, 5, 6],
#         [6, 7, 8]],

#        [[4, 4, 5],
#         [2, 4, 5],
#         [5, 6, 7]]])

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 5, 4]],

       [[1, 2, 3],
        [3, 5, 6],
        [6, 7, 8]],

       [[4, 4, 5],
        [2, 4, 5],
        [5, 6, 7]]])

## 2. Properties of Numpy Array

In [5]:
# Shape Back us the shape of the array in the form of (content countings,cols, rows)
print("Shape of One dim array:",one_dim_array.shape)
print("Shape of Two dim array:",two_dim_array.shape)
print("Shape of Three dim array:",three_dim_array.shape)

Shape of One dim array: (7,)
Shape of Two dim array: (3, 3)
Shape of Three dim array: (3, 3, 3)


In [6]:
# total elements of the array or the size of an array
print("Size of One dim array:",one_dim_array.size)
print("Size of Two dim array:",two_dim_array.size)
print("Size of Three dim array:",three_dim_array.size)

Size of One dim array: 7
Size of Two dim array: 9
Size of Three dim array: 27


In [7]:
#checking the dimensions of array
print("Dimensions of One dim array:",one_dim_array.ndim)
print("Dimensions of Two dim array:",two_dim_array.ndim)
print("Dimensions of Three dim array:",three_dim_array.ndim)

Dimensions of One dim array: 1
Dimensions of Two dim array: 2
Dimensions of Three dim array: 3


In [8]:
# Checking the datatype of an array
print("Data-Type of One dim array:",one_dim_array.dtype)
print("Data-Type of Two dim array:",two_dim_array.dtype)
print("Data-Type of Three dim array:",three_dim_array.dtype)

Data-Type of One dim array: int64
Data-Type of Two dim array: int64
Data-Type of Three dim array: int64


## 3.  Special Functions of Numpy Arrray

In [9]:
# Determine the type of an array
print("Type of One dim array:",type(one_dim_array))
print("Type of Two dim array:",type(two_dim_array))
print("Type of Three dim array:",type(three_dim_array))

Type of One dim array: <class 'numpy.ndarray'>
Type of Two dim array: <class 'numpy.ndarray'>
Type of Three dim array: <class 'numpy.ndarray'>


In [10]:
# Checking the ones() and zeros() function of array
once_array=np.ones((3,3))
zeros_array=np.zeros((3,3,3))
display(once_array)
display(zeros_array)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# arange() function  as same as loop range()
arranged_array = np.arange(1,28).reshape(3,3,3)
display(arranged_array,type(arranged_array),arranged_array.ndim,arranged_array.dtype)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

numpy.ndarray

3

dtype('int64')

In [12]:
#linspace() function 
#reshape() function (dimension, row, columns)
reshaped_array=arranged_array.reshape(9,3)
display(reshaped_array,reshaped_array.ndim)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

2

In [13]:
#converting the multidimentional aarray to one dim array using ravel() 
raveled_array=arranged_array.ravel()
display(raveled_array,raveled_array.ndim)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

1

In [14]:
#converting the multidimentional aarray to one dim array using flatten()
Flatten_array=arranged_array.flatten()
display(Flatten_array,Flatten_array.ndim)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

1

In [15]:
#transpose the matrix (change row into column && column into row) using transpose()
transposed_array=arranged_array.transpose()
print('Untranspose array : \n',arranged_array,' \n \n Transposed: \n \n',transposed_array)

Untranspose array : 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]  
 
 Transposed: 
 
 [[[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]

 [[ 3 12 21]
  [ 6 15 24]
  [ 9 18 27]]]


## 4. Performing Arithmatic  operations on Numpy array or data

In [16]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(10,19).reshape(3,3)
print(arr1,'\n \n',arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [17]:
# addition of arrays and subtraction of arrays 
display(
    # Addition Via + arithmatic Operator
    arr1+arr2,
    #addition Via add() function
    np.add(arr1,arr2),
    # Subtract Via - arithmatic Operator
    arr2-arr1,
    # Addition Via Subtract Function
    np.subtract(arr2,arr1)
       )

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [18]:
# Add by (+) or np.add()
# Subtraction using (-) and np.subtract()
# Multipliction by (*) and np.multiply()

print('(*): \n',arr1*arr2)
print('np.multiply():\n',np.multiply(arr1,arr2))

# Divide by (/) and np.divide()
print('(/):\n',arr1/arr2)
print('np.divide():\n',np.divide(arr1,arr2))

(*): 
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
np.multiply():
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
(/):
 [[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
np.divide():
 [[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [19]:
# Warnning: Now * is the multiplication of the matrix not a product of matrix 
# Product of matrix by (@) and np.dot()
print("Product Of array using @: \n",arr1@arr2)
print("Product Of array using dot(): \n",np.dot(arr1,arr2))

Product Of array using @: 
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
Product Of array using dot(): 
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [20]:
# Cross of the matrix by the np.cross()
np.cross(arr1,arr2)

array([[-9, 18, -9],
       [-9, 18, -9],
       [-9, 18, -9]])

In [21]:
# Max Value of the matrix
print(arr1.max())
# getting the index of max number
print(arr1.argmax())
# getting the max values in the row
print(arr1.max(axis=1))
#getting the min values index in row
print(arr1.argmax(axis=1))
# getting the max values in the column 
print(arr1.max(axis=0))
#getting the min values index in column
print(arr1.argmax(axis=0))

9
8
[3 6 9]
[2 2 2]
[7 8 9]
[2 2 2]


In [22]:
# Getting min value of the matrix
print(arr2.min())
#getting the index of the min value 
print(arr2.argmin())
# getting the max values in the row
print(arr2.min(axis=1))
#getting the min values index in row
print(arr2.argmin(axis=1))
# getting the max values in the column
print(arr2.min(axis=0))
#getting the min values index in column
print(arr2.argmin(axis=0))

10
0
[10 13 16]
[0 0 0]
[10 11 12]
[0 0 0]


In [24]:
# Self Addition of matrix
print(np.sum(arr2))
# Self Addition of matrix by row
print(np.sum(arr2,axis=1))
# Self Addition of matrix by column
print(np.sum(arr2,axis=0))

126
[33 42 51]
[39 42 45]


In [25]:
# Mean of the Matrix
print(np.mean(arr2))
# Mean of the Matrix by Row
print(np.mean(arr2 , axis = 1))
# Mean of the Matrix by Column
print(np.mean(arr2 , axis = 0))

14.0
[11. 14. 17.]
[13. 14. 15.]


In [26]:
# square root of the matrix by each element
np.sqrt(arr2)

array([[3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069]])

In [27]:
# Standerd Division of the matrix
np.std(arr2)

2.581988897471611

In [28]:
#exponent of the matrix each element
np.exp(arr2)

array([[2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07]])

In [29]:
#log of matrix by each element 
print(np.log(arr2))
# log10 of matrix
print(np.log10(arr2))

[[2.30258509 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502 ]
 [2.77258872 2.83321334 2.89037176]]
[[1.         1.04139269 1.07918125]
 [1.11394335 1.14612804 1.17609126]
 [1.20411998 1.23044892 1.25527251]]


## 5. Array Slicing of numpy

In [30]:
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [31]:
#getting a row by index
arr2[2,:]

array([16, 17, 18])

In [32]:
arr2[2].ndim

1

In [33]:
#getting a column by index
arr2[:,2]

array([12, 15, 18])

In [34]:
arr2[:,2].ndim

1

In [35]:
# getting a value on the specific index
arr2[1,1]

14

In [36]:
# getting a value on the specific index
arr2[1,1].ndim

0

In [37]:
#getting data from matrix 
arr2[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [38]:
#getting full matrix by [:] or [::] 
arr2[:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [39]:
arr2[::]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [40]:
# itemsize of an array 
arr2.itemsize

8

In [41]:
# array Concatination and split
np.concatenate((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [42]:
# concatenate by row
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [43]:
# Concatenation by column
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [44]:
#vertical Concatenate the matrix
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [45]:
# horizontally concatenate the array
hs=np.hstack((arr1,arr2))
hs

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [ ]:
#spliting arrays 
np.split(hs,3)

In [46]:
#row wise spliting
print(np.split(hs,3,axis=0))

[array([[ 1,  2,  3, 10, 11, 12]]), array([[ 4,  5,  6, 13, 14, 15]]), array([[ 7,  8,  9, 16, 17, 18]])]


In [47]:
#column wise spliting
print(np.split(hs,2,axis=1))

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


## 6. Trigonometrix in data

In [48]:
# np.sin(angle), np.cos(angle), np.tan(angle)
print(np.sin(130))
print(np.cos(130))
print(np.tan(130))
print(np.sin(30))
print(np.sin(90))

-0.9301059501867618
-0.3672913304546965
2.5323384274693232
-0.9880316240928618
0.8939966636005579


## 7. Random Sampling with Random Package

In [49]:
import random

In [50]:
# Creating an array
np.random.random([3,3])

array([[0.79337973, 0.94264964, 0.87265257],
       [0.18739157, 0.67697166, 0.13404428],
       [0.54585826, 0.42988722, 0.98462246]])

In [51]:
np.random.randint(1,4,(4,4))

array([[2, 1, 3, 3],
       [1, 2, 2, 2],
       [1, 1, 3, 2],
       [3, 2, 2, 2]])

In [52]:
np.random.seed(10)
np.random.rand(3)

array([0.77132064, 0.02075195, 0.63364823])

In [53]:
np.random.rand(3,3)

array([[0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084],
       [0.08833981, 0.68535982, 0.95339335]])

In [54]:
np.random.randn(3,3)

array([[ 0.00429143, -0.17460021,  0.43302619],
       [ 1.20303737, -0.96506567,  1.02827408],
       [ 0.22863013,  0.44513761, -1.13660221]])

In [55]:
np.random.choice(3)

1

## 8. String Methods via Numpy

In [ ]:
# np.char.add()
# np.char.uppercase()
# np.char.lowercase()
# np.char.split()

**thankyou**
